### ISSUE TITLE
Samples missing

### ISSUE THREAD

**Issue by SenchoPens** [guozixunnicolas/FundamentalMusicEmbedding#1]
Dear authors,
In the paper it is mentioned that the samples are in the GitHub repository, but in fact currently they are not. I am very interested by your research, can you provide any information on when to expect them?

**Comment by guozixunnicolas** [comment]
Hi there,

Thank you for your interest in FME. The datasets (TheoryTab&Wikifonia) used are open-sourced and are available online. I'm not sure whether I am allowed to upload the entire pre-processed dataset though due to license issues. I am currently on leave and I could upload some sample data when I'm back (in about 2 weeks?).

If you want to generate some sample music, I have uploaded the trained checkpoints (in the checkpoints folder, do check the config file for the correct RIPO transformer setting) and a generation script. 

Let me know if you need any further help! 

Best,

Nicolas

**Comment by SenchoPens** [comment]
Hi, I was asking about the generated music, now it's clear, thanks!
